language: python
python:
  - "2.7"

install:
    - pip install robotframework
    - pip install robotframework-selenium2library
    #  - pip install selenium
    #  - pip install decorator
    #  - pip install docutils
    #  - "if [[ ${BROWSER} == 'ie' ]]; then pip install ie_only_pkg; fi"

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

script:
    #  - "python test/run_tests.py python $BROWSER --noncritical ignore_${BROWSER}_error"
    - cd WebDemo/demoapp && bash -c 'python server.py&' && sleep 5 && netstat -nplt && cd ../login_tests && curl http://localhost:7272/ && pybot valid_login.txt
    #  - cd WebDemo/login_tests && pybot valid_login.txt
env:
    matrix:
        - BROWSER=firefox
          #- BROWSER=ie # will be added when we have completed SauceLabs CI
          #- BROWSER=safari # will be added after #247 merged
