language: python
python:
  - "2.7"

install:
    - pip install robotframework
    - pip install robotframework-selenium2library
    #  - pip install selenium
    #  - pip install decorator
    #  - pip install docutils
    #  - "if [[ ${BROWSER} == 'ie' ]]; then pip install ie_only_pkg; fi"

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

script:
    #  - "python test/run_tests.py python $BROWSER --noncritical ignore_${BROWSER}_error"
    #  - cd WebDemo/demoapp && bash -c 'python server.py&' && sleep 3 && cd ../login_tests && pybot valid_login.txt
    - bash -c 'python WebDemo/demoapp/server.py&' && sleep 3 && pybot --pythonpath WebDemo/login_tests WebDemo/login_tests/
    #  - cd WebDemo/login_tests && pybot valid_login.txt

after_success:
    - ./update-gh-pages.sh

env:
    matrix:
        - BROWSER=firefox
          #- BROWSER=ie # will be added when we have completed SauceLabs CI
          #- BROWSER=safari # will be added after #247 merged
    global:
        secure: HRqQQOy5BheF8rQEWoHLLSPZ826d2MuqiFlHuZ4zRJ7AsxLk0sDy+rixKQjaBXF07PwGEWnNAR1Yp7Rd1zmL9pmQUqYnDO/wAORtJ9ZgQgkazrm1TuJ3y6N/mMP3z0bG401HxeaSWupCLk5WJ89/DVG+U8DLgRL+cNJAqM6X690=
